### ISSUE TITLE
ispconfig3_autoreply broken ?

### ISSUE THREAD

**Issue by teadur** [w2c/ispconfig3_roundcube#37]
Fatal error: Uncaught exception 'Exception' with message 'DateTime::__construct() [<a href='datetime.--construct'>datetime.--construct</a>]: Failed to parse time string (@) at position 0 (@): Unexpected character' in /usr/share/squirrelmail/roundcube/plugins/ispconfig3_autoreply/ispconfig3_autoreply.php:138 Stack trace: #0 /usr/share/squirrelmail/roundcube/plugins/ispconfig3_autoreply/ispconfig3_autoreply.php(138): DateTime->__construct('@') #1 [internal function]: ispconfig3_autoreply->gen_form(Array) #2 /usr/share/squirrelmail/roundcube/program/include/rcmail_output_html.php(948): call_user_func(Array, Array) #3 [internal function]: rcmail_output_html->xml_command(Array) #4 /usr/share/squirrelmail/roundcube/program/include/rcmail_output_html.php(833): preg_replace_callback('/<roundcube:([-...', Array, '<roundcube:obje...') #5 /usr/share/squirrelmail/roundcube/program/include/rcmail_output_html.php(509): rcmail_output_html->parse_xml('<roundcube:obje...') #6 /usr/share/squirrelmail/roundcube/program/include/rcmail_output in /usr/share/squirrelmail/roundcube/plugins/ispconfig3_autoreply/ispconfig3_autoreply.php on line 138

**Comment by teadur** [comment]
most likely misconfiguration, tested and working with roundcube1.1-rc
