### ISSUE TITLE
php error after following the manual installation instructions

### ISSUE THREAD

**Issue by ApertureDevelopment** [w2c/ispconfig3_roundcube#82]
Hello,

I installed the tools but now I get overthrown with those errors:
```
[22-Jul-2018 10:20:42 Europe/Berlin] PHP Fatal error:  Uncaught Error: Class 'SoapClient' not found in /var/lib/roundcube/plugins/ispconfig3_account/ispconfig3_account.php:17
Stack trace:
#0 /usr/share/roundcube/program/lib/Roundcube/rcube_plugin_api.php(99): ispconfig3_account->init()
#1 /usr/share/roundcube/program/include/rcmail.php(135): rcube_plugin_api->init(Object(rcmail), 'settings')
#2 /usr/share/roundcube/program/include/rcmail.php(79): rcmail->startup()
#3 /usr/share/roundcube/index.php(43): rcmail::get_instance(0, NULL)
#4 {main}
  thrown in /var/lib/roundcube/plugins/ispconfig3_account/ispconfig3_account.php on line 17
```

**Comment by horfic** [comment]
Hi,
It sounds like you are missing the php soap extensions. 

Can you check that please. 

Cheers, 
Horfic
